### ISSUE TITLE
Codzienny Scrum

### ISSUE THREAD

**Issue by Kreci** [Kreci/Projekt-INPG---Baza-danych#1]
Przypominam o codziennym scrumie, proszę na bieżąco informować o tym, co robicie i z czym macie problemy.

**Comment by Kreci** [comment]
Przypominam również, że gdybyście mieli jakiekolwiek trudności, możecie śmiało pisać tickety, reszta zespołu postara się pomóc.

**Comment by DawidSkoczny** [comment]
Nie zapominajcie o codziennym scrumie, proszę zapoznać się z nowo powstałymi kamieniami milowymi.
