### ISSUE TITLE
Niedziałający kreator

### ISSUE THREAD

**Issue by Pegas868** [Kreci/Projekt-INPG---Baza-danych#2]
W kreatorze nie zdefiniowano struktury przekazywanej jako argument która ma być umieszczona w drzewie. Nadaj jej jakąś nazwę, nie będę ci grzebał w tym kodzie

**Comment by Pegas868** [comment]
I trzeba będzie przekazywać to jakoś w funkcji insert, tam też trzeba będzie podać tą strukturę. Nie wiem jak chcesz żeby to działało, popraw to a wieczorem spróbuję napisać maina z tym

**Comment by Kreci** [comment]
Przekazuję tam strukturę note, której nadałeś nazwę data. W definicji funkcji createNode w creator.c był tylko typ argumentu, brakowało konkretnego obiektu (data* zamiast data* data). Wydaje mi się, że powinno być okej. Jeśli nie o to chodzi, to nie widzę, co miałoby być problemem.

**Comment by Pegas868** [comment]
Dokładnie o to chodzi, wieczorem jak wroce sie biore za maina. Jeszcze w
funkcji insert funkcja create jest wywolywana bez argumentu z tego co
kojarze
10 maj 2016 18:55 "Kreci" <notifications@github.com> napisał(a):

**Comment by Kreci** [comment]
Poprawione, jeśli będą jeszcze jakieś problemy, to pisz.
