### ISSUE TITLE
Problem z fDisplay() lub gdzieś indziej

### ISSUE THREAD

**Issue by Kreci** [Kreci/Projekt-INPG---Baza-danych#3]
Coś jest nie tak, nie wiem tylko gdzie leży błąd.
Gdy wpiszę kilka elementów do drzewa i wyświetlę je, to pierwszy element pojawia się dwa razy lub też raz, ale na końcu, zamiast na początku.
Gdy każę wyświetlić puste drzewo, program wypisuje "Baza jest pusta", mimo, że niczego takiego nie kazałem mu robić (nie przy wywołaniu funkcji fDisplay).
Może mój kompilator i komputer wariuje, nie wiem. Niech ktoś spróbuje skompilować te pliki i zobaczyć, co mu wyjdzie.

**Comment by DawidSkoczny** [comment]
Wyświetlenie pustego drzewa nie powoduje wyświetlenie napisu "Baza jest pusta", możliwe że już zostało to naprawione.
Podobnie z wpisywaniem elementów.

**Comment by Kreci** [comment]
Skompilowałem od nowa pliki pobrane z githuba i działa dobrze. Musiałem coś namieszać w moich plikach na kompie, ale nigdzie błędu nie widziałem, może wina CodeBlocksa. Tak czy siak, sprawa załatwiona.
