### ISSUE TITLE
Funkcja usuwająca

### ISSUE THREAD

**Issue by Kreci** [Kreci/Projekt-INPG---Baza-danych#6]
Problem z czyszczeniem roota!
Możliwe rozwiązanie - przekazywanie do funkcji wskaźnika na root zamiast roota

**Comment by Pegas868** [comment]
Ale zdajesz sobie sprawę, że trzeba by wtedy dosłownie przepisać cały program żeby działał na wskaźniku na drzewo a nie na drzewie?

**Comment by Kreci** [comment]
Przypominam, że trzeba się tym zająć.

**Comment by Pegas868** [comment]
Zalatwione
