### ISSUE TITLE
Polskie znaki w konsoli

### ISSUE THREAD

**Issue by DawidSkoczny** [Kreci/Projekt-INPG---Baza-danych#7]
Brakuje polskich znaków w programie, występuje problem z ich wyświetlaniem w konsoli.
Proponowane rozwiązanie znajduje się na stronie http://forum.purepc.pl/topic/98056-polskie-znaki-w-c/

**Comment by Kreci** [comment]
Podobno może pomóc dodanie  
     setlocale(LC_ALL,"");
na początku maina.
Inną opcją jest zabawa z ustawieniami kodowania plików oraz Code::Blocksa/innego używanego programu.

**Comment by Kreci** [comment]
Wydaje mi się, że nawet jeśli da się to zrobić, to byłoby to bardzo trudne i nie mamy na to czasu. Proponuję po prostu zostać przy braku polskich znaków.

**Comment by DawidSkoczny** [comment]
Gdy wpiszemy taki kod:

#include <string.h>
#include <stdio.h>
#include <locale.h>

int main( void ) {
    setlocale( LC_ALL, "pl_PL" );

    printf("ąćęłńóśżźĄĆĘŁŃÓŚŻŹ\n");
    char a[20], b[20];
    scanf("%s %s",a,b);
    puts(a);
    puts(b);

    return 0;
}

Znaki wpisywane do konsoli i wczytane z klawiatury są znakami polskimi. Jednak funkcja printf() dla znaków przygotowanych w czasie kompilacji nie sprawdza się. Gdy zmienimy argumenty setlocale na:

    setlocale( LC_ALL, "" );

Znaki wcześniej przygotowane są okej, te wpisane przez użytkownika nie.

Wynika to z tego, że polskie znaki różnią się kodowaniem. Tekst z kodu jest (w tym przypadku) kodowany w ANSI, a z konsoli chyba w Windows-1250. Na systemach Linux, prawdopodobnie działa takie wyświetlanie znaków Unicode pod Linuksem:

#include <cstdio>
#include <iostream>

int main()
{
    //	setlocale(LC_ALL, "pl_PL.UTF-8");
    //	setlocale(LC_ALL, "en_US.UTF-8");
    setlocale( LC_ALL, "C.UTF-8" );
    const wchar_t * text = L"Вітаю, шаноўны спадар!";
    wprintf( L"printf wchar_t*: '%ls'\n", text );
    wprintf( L"Hello world! ąćęłóżń\n" );
    std::wcout << L"Hello world! ąćęłóżń\n" << text;
    return 0;
}

Jednak nie mam możliwości go przetestować, a także są obawy, że po konwersji do C może przestać działać poprawnie.

Można też spróbować zmienić czcionkę w konsoli na tą posiadającą polskie znaki.
Jeszcze poszukam lepszych metod i dam wam znać.

**Comment by DawidSkoczny** [comment]
Na dole kolejny sposób na C++ http://cpp0x.pl/forum/temat/?id=7271
Więcej nie znalazłem, lub nie działało.

**Comment by DawidSkoczny** [comment]
*include zniknęło.
#include < stdio.h >
#include < locale.h >
#include < stdlib.h >

**Comment by Kreci** [comment]
Z uwagi na ograniczenia czasowe projektu, rezygnujemy z tej funkcjonalności.
